# Generated by Django 2.1.8 on 2019-04-14 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20190108_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smscontact',
            options={'ordering': ['-created_on', '-updated_on']},
        ),
        migrations.RenameField(
            model_name='smscontact',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='smscontact',
            old_name='updated_at',
            new_name='updated_on',
        ),
    ]
