# Generated by Django 2.1.8 on 2019-05-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='crm_id',
            field=models.TextField(blank=True, verbose_name='suite crm id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='idp_uuid',
            field=models.TextField(blank=True, verbose_name='idp uuid'),
        ),
        migrations.AlterField(
            model_name='account',
            name='plan',
            field=models.CharField(choices=[('community', 'Community'), ('core', 'Core'), ('vip-basic', 'VIP Basic'), ('vip-standard', 'VIP Standard'), ('vip-premium', 'VIP Premium'), ('vip-enterprise', 'VIP Enterprise'), ('partner', 'Partner')], default='community', max_length=25, verbose_name='support plan'),
        ),
    ]
