# Generated by Django 2.1.8 on 2019-06-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20190528_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_auto',
            field=models.BooleanField(default=False, verbose_name='is auto'),
        ),
    ]
