# Generated by Django 2.2.3 on 2019-08-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_account_is_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='plan',
            field=models.CharField(choices=[('community', 'Community'), ('core', 'Core'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise'), ('vip', 'VIP'), ('partner', 'Partner')], default='community', max_length=25, verbose_name='support plan'),
        ),
    ]
