export const PURGE_AUTH = 'purgeAuth'
export const SET_AUTH = 'setUser'
export const SET_ERROR = 'setError'
export const SET_LOGIN_URL = 'setLoginURL'
export const SET_LOGOUT_URL = 'setLogoutUrl'
export const PURGE_EMAIL_ERROR = 'purgeEmailError'
export const PURGE_COUNTRY_ERROR = 'purgeCountryError'
export const PURGE_TIMEZONE_ERROR = 'purgeTimezoneError'
