# Generated by Django 2.2.3 on 2019-08-05 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190619_1647'),
        ('suitecrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_id', models.CharField(max_length=150, unique=True, verbose_name='crm id')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Address')),
            ],
        ),
        migrations.CreateModel(
            name='CrmContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_id', models.CharField(max_length=150, unique=True, verbose_name='crm id')),
                ('first_name', models.CharField(max_length=150, verbose_name='crm id')),
                ('last_name', models.CharField(max_length=150, verbose_name='crm id')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suitecrm.CrmAccount')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Address')),
            ],
        ),
        migrations.CreateModel(
            name='CrmEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='crm id')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='suitecrm.CrmContact')),
            ],
        ),
    ]
