# Generated by Django 2.2.3 on 2019-08-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suitecrm', '0002_crmaccount_crmcontact_crmemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmaccount',
            name='plan',
            field=models.CharField(choices=[('community', 'Community'), ('core', 'Core'), ('vip-basic', 'VIP Basic'), ('vip-standard', 'VIP Standard'), ('vip-premium', 'VIP Premium'), ('vip-enterprise', 'VIP Enterprise'), ('partner', 'Partner')], default='community', max_length=25, verbose_name='support plan'),
        ),
    ]
