# Generated by Django 2.1.8 on 2019-05-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crm_id',
            field=models.TextField(blank=True, verbose_name='suite crm id'),
        ),
    ]
