# Generated by Django 2.2.3 on 2019-08-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20190805_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='crm_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='crm id'),
        ),
        migrations.AddField(
            model_name='company',
            name='named_contacts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='named contacts'),
        ),
        migrations.AddField(
            model_name='company',
            name='plan',
            field=models.CharField(choices=[('community', 'Community'), ('core', 'Core'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise'), ('vip', 'VIP'), ('partner', 'Partner')], default='community', max_length=25, verbose_name='support plan'),
        ),
        migrations.AddField(
            model_name='company',
            name='review_hours',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='review hours'),
        ),
        migrations.AddField(
            model_name='company',
            name='support_hours',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='support hours'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, verbose_name='website'),
        ),
    ]
