# Generated by Django 2.1.8 on 2019-04-14 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_on', '-updated_on']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_on', '-updated_on']},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='tickethistory',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
