# Generated by Django 2.2.2 on 2019-06-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190610_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='gluu_server',
            field=models.CharField(max_length=255),
        ),
    ]
